'use client';
import Navbar from '../components/Navbar/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
// Next auth
import AuthProvider from '../components/AuthProvider/AuthProvider';
import { usePathname } from 'next/navigation';
import Footer from '../components/Footer/Footer';
// Toastify
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// Redux
import { persistor, store } from '../redux/store';
import { Provider } from 'react-redux';
// Persist
import { PersistGate } from 'redux-persist/integration/react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    const pathname = usePathname();
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <AuthProvider>
                    <Provider store={store}>
                        <PersistGate loading={null} persistor={persistor}>
                            {/* <div className="w-screen h-screen overflow-x-hidden bg-gray-800 text-white"> */}
                            {pathname.includes('/seller') ? (
                                <div className="w-screen h-screen overflow-x-hidden">
                                    <ToastContainer />
                                    {children}
                                </div>
                            ) : (
                                <div className="w-screen h-screen overflow-x-hidden">
                                    <ToastContainer />
                                    <Navbar />
                                    {children}
                                    <Footer />
                                </div>
                            )}
                        </PersistGate>
                    </Provider>
                </AuthProvider>
            </body>
        </html>
    );
}
